# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('year', models.CharField(default='', max_length=200)),
                ('director', models.CharField(default='', max_length=200)),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('plot_description', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
