# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_auto_20160517_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='plot_description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
